# Generated by Django 5.2.2 on 2025-06-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CORE_SUBJECTS', models.CharField()),
            ],
        ),
    ]
