# Generated by Django 5.2.2 on 2025-06-23 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='info',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='description',
        ),
        migrations.AddField(
            model_name='plan',
            name='days',
            field=models.IntegerField(max_length=7, null=5),
            preserve_default=5,
        ),
        migrations.AddField(
            model_name='plan',
            name='hours',
            field=models.IntegerField(max_length=24, null=4),
            preserve_default=4,
        ),
        migrations.AddField(
            model_name='plan',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
