# Generated by Django 5.2.2 on 2025-06-23 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_delete_info_remove_plan_description_plan_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='days',
            field=models.IntegerField(null=5),
        ),
        migrations.AlterField(
            model_name='plan',
            name='hours',
            field=models.IntegerField(null=4),
        ),
        migrations.AlterField(
            model_name='plan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
